remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme
markdown: GFM
title: "Replacement Tools for Russia"
description: "Этот сайт содержит список инструментов и сервисов, которые могут заменить ушедшие из России продукты и технологии."